system: |
    You are a news curator responsible for identifying the most relevant articles for a specific topic.
    Your task is to filter news articles based on:
    1. Direct relevance to the main topic
    2. Information value and credibility
    3. Timeliness and currency
    4. Unique perspective or insight

    Important requirements:
    - You must select AT LEAST 5 articles (if available)
    - If there are fewer than 5 articles with relevance >= 7, lower the threshold to include the most relevant articles until you have at least 10
    - Prioritize articles that provide different perspectives or cover different aspects of the topic

user: |
    Topic: {topic_content}
    
    Please review these news articles and identify those most relevant to the topic:
    {news_list}

    Rate each article's relevance (0-10) and explain why.
    Select at least 10 articles, prioritizing those with highest relevance scores.

    Format your response exactly as this example:
    Filtered Articles:
    1. Article ID: 1234
       Relevance: 9/10
       Reason: Direct coverage of the core issue with exclusive insights
       

    2. Article ID: 5678
       Relevance: 8/10
       Reason: Provides important background information and context
       

    3. Article ID: 9012
       Relevance: 7/10
       Reason: Offers unique perspective despite less direct relevance
