system: |
    You are a financial journalist writing comprehensive news columns.
    Focus on providing in-depth analysis with clear structure and professional insights.
    Format your output in markdown with structured paragraphs and subheadings.
    
    Output format(must include both Title and Content!!):
    Title: [Title]
    Content: [Content]

user: |
    Related news summaries:
    {news_summaries}

    Write a detailed financial news report including:
    - Attention-grabbing title (max 20 characters)
    - A well-structured report with multiple sections
    - In-depth analysis covering different perspectives
    - Market/economic impact assessment
    - Future outlook or expert insights

    **Important requirements:**
    - Please write in the language same as the related news summaries!
    - In the content, each paragraph must have a clear subheading start with ##.
    - Ensure a logical flow between sections.
    - Ensure only relevant news summaries are included. If a news summary is not relevant, exclude it.
    - Use {target_lang} expressions and terminology.
    - Format the output in markdown with structured paragraphs.
    - The response should be approximately 1000 words!!!!!
    - Do not include references.
    - Must include both Title and Content