# System configuration
system:
  default_region: us
  log_level: INFO
  max_topics: 5
  max_news_per_topic: 10
  min_word_count: 500
  max_word_count: 2000

# Region configurations
regions:
  # Taiwan region
  tw:
    display_name: "Taiwan"
    timezone: "Asia/Taipei"
    main_language: "zh_tw"
    input_file: "data/tw_news_{date}.json"
    weighted_sources:
      "Economy News": 2
      "Anue News": 2
      "MoneyDJ TW News": 2
      "Tech News": 2
    stopwords:
      - "的"
      - "是"
      - "在"
      - "了"
      - "和"
      - "與"
      - "就"
      - "都"
      - "而"
      - "及"
      - "著"
      - "或"
      - "說"
      - "來"
      - "但"
      - "又"
      - "要"
      - "會"
      - "等"
      - "很"
      - "好"
      - "將"
      - "還"
      - "能"
      - "得"
      - "那"
      - "這"
      - "於"
      - "以"
      - "之"
      - "時"
      - "為"
      - "他"
      - "沒"
      - "我"
      - "你"
      - "她"
      - "它"
      - "有"
      - "可"
      - "個"
      - "麼"
      - "去"
      - "把"

  # United States region
  us:
    display_name: "United States"
    timezone: "America/New_York"
    main_language: "eng"
    input_file: "data/us_news_{date}.json"
    weighted_sources:
      "Bloomberg": 2
      "Reuters": 2
      "CNN News": 2
      "TechCrunch": 2
    stopwords:
      - "the"
      - "be"
      - "to"
      - "of"
      - "and"
      - "a"
      - "in"
      - "that"
      - "have"
      - "i"
      - "it"
      - "for"
      - "not"
      - "on"
      - "with"
      - "he"
      - "as"
      - "you"
      - "do"
      - "at"
      - "this"
      - "but"
      - "his"
      - "by"
      - "from"
      - "they"
      - "we"
      - "say"
      - "her"
      - "she"
      - "or"
      - "an"
      - "will"
      - "my"
      - "one"
      - "all"
      - "would"
      - "there"
      - "their"
      - "what"
      - "so"
      - "up"
      - "out"
      - "if"
      - "about"
      - "who"
      - "get"
      - "which"
      - "go"
      - "me"
      - "when"
      - "make"
      - "can"
      - "like"
      - "time"
      - "no"
      - "just"
      - "him"
      - "know"
      - "take"
      - "people"
      - "into"
      - "year"
      - "your"
      - "good"
      - "some"
      - "could"
      - "them"
      - "see"
      - "other"
      - "than"
      - "then"
      - "now"
      - "look"
      - "only"
      - "come"
      - "its"
      - "over"
      - "think"
      - "also"

  # Vietnam region
  vt:
    display_name: "Vietnam"
    timezone: "Asia/Ho_Chi_Minh"
    main_language: "vi"
    input_file: "data/vt_news_{date}.json"
    weighted_sources:
      "VnExpress": 1.2
      "Tuoi Tre": 1.1
      "Thanh Nien": 1.0
      "Nanhan News": 0.9
    stopwords:
      - "của"
      - "và"
      - "các"
      - "có"
      - "được"
      - "trong"
      - "đã"
      - "với"
      - "những"
      - "cho"
      - "này"
      - "về"
      - "là"
      - "để"
      - "đến"
      - "theo"
      - "như"
      - "từ"
      - "khi"
      - "tại"
      - "trên"
      - "một"
      - "không"
      - "phải"
      - "còn"
      - "bị"
      - "vì"
      - "do"
      - "vào"
      - "cùng"
      - "sau"
      - "ra"
      - "ngoài"
      - "thì"
      - "việc"
      - "nên"
      - "làm"
      - "tới"
      - "mà"
      - "lúc"
      - "rằng"
      - "lại"
      - "cũng"
      - "được"
      - "đi"
      - "nếu"
      - "đây"
      - "biết"
      - "bạn"
      - "anh"
      - "những"
      - "nhưng"
      - "vẫn"
      - "nhiều"
      - "sẽ"
      - "phải"
      - "vậy"
      - "tôi"
      - "họ"
      - "bởi"
      - "về"
      - "đang"
      - "giữa"
      - "chỉ"
      - "ngoài"
      - "đều"
      - "mới"
      - "thật"
      - "sau"
      - "or"
      - "and"
      - "the"
      - "để"
      - "cho"
      - "công"
      - "bộ"
      - "theo"
      - "tại"
      - "trong"
      - "trên"
      - "dưới"
      - "đã"
      - "sẽ"
      - "từ"
      - "lên"
      - "xuống"
      - "đến"
      - "về"
      - "qua"


